application: nevadacountymakes-hrd
version: v2-1-1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /cleanup_sessions
  script: cleanup_sessions.py
  login: admin

- url: /update_featured
  script: update_featured.py
  login: admin

- url: /ipn
  script: ipn.py

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: ncm.py

error_handlers:
- file: error.html

builtins:
- datastore_admin: on
